services:
  - type: web
    name: viable-solution-web-app
    runtime: docker
    branch: main
    plan: free
    dockerfilePath: ./dockerfile
    autoDeploy: true

databases:
  - name: viable-solution-db
    plan: starter