# Generated by Django 4.2.16 on 2026-05-28 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viable_graph_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={},
        ),
        migrations.AddField(
            model_name='problem',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='problem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='problem_photos/'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('WASTE', 'ปริมาณขยะและเศษอาหาร'), ('POLLUTION', 'มลพิษและการใช้พลังงาน'), ('WATER', 'การจัดการน้ำ'), ('APP', 'ระบบแอปพลิเคชันและการสื่อสาร'), ('COMMUNITY', 'การมีส่วนร่วมของชุมชน (ประชาคมจุฬาฯ)')], default='WASTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROGRESS', 'กำลังดำเนินการแก้ไข'), ('COMPLETED', 'แก้ไขเสร็จสิ้นแล้ว')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='viable_graph_app.problem'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
