# Generated by Django 4.2.16 on 2026-06-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viable_graph_app', '0005_comment_problemgroup_remove_suggestion_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(choices=[('SCIENCE', 'คณะวิทยาศาสตร์'), ('ENGINEERING', 'คณะวิศวกรรมศาสตร์'), ('ARTS', 'คณะอักษรศาสตร์'), ('COMMERCE_ACCOUNTANCY', 'คณะพาณิชยศาสตร์และการบัญชี'), ('POLITICAL_SCIENCE', 'คณะรัฐศาสตร์'), ('LAW', 'คณะนิติศาสตร์'), ('MEDICINE', 'คณะแพทยศาสตร์'), ('ARCHITECTURE', 'คณะสถาปัตยศาสตร์'), ('OTHERS', 'บุคลากร / อื่นๆ')], default='SCIENCE', max_length=200),
        ),
    ]
