# Generated by Django 4.2.16 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viable_graph_app', '0006_alter_userprofile_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(choices=[('EDUCATION', 'คณะครุศาสตร์'), ('PSYCHOLOGY', 'คณะจิตวิทยา'), ('DENTISTRY', 'คณะทันตแพทยศาสตร์'), ('LAW', 'คณะนิติศาสตร์'), ('COMMUNICATION_ARTS', 'คณะนิเทศศาสตร์'), ('NURSING', 'คณะพยาบาลศาสตร์'), ('COMMERCE_ACCOUNTANCY', 'คณะพาณิชยศาสตร์และการบัญชี'), ('POLITICAL_SCIENCE', 'คณะรัฐศาสตร์'), ('SCIENCE', 'คณะวิทยาศาสตร์'), ('SPORTS_SCIENCE', 'คณะวิทยาศาสตร์การกีฬา'), ('ENGINEERING', 'คณะวิศวกรรมศาสตร์'), ('FINE_APPLIED_ARTS', 'คณะศิลปกรรมศาสตร์'), ('ARCHITECTURE', 'คณะสถาปัตยกรรมศาสตร์'), ('ALLIED_HEALTH_SCIENCES', 'คณะสหเวชศาสตร์'), ('VETERINARY_SCIENCE', 'คณะสัตวแพทยศาสตร์'), ('ARTS', 'คณะอักษรศาสตร์'), ('INTEGRATED_AGRICULTURE', 'คณะเกษตรศาสตร์บูรณาการ'), ('PHARMACEUTICAL_SCIENCES', 'คณะเภสัชศาสตร์'), ('ECONOMICS', 'คณะเศรษฐศาสตร์'), ('MEDICINE', 'คณะแพทยศาสตร์'), ('OTHERS', 'บุคลากร / หน่วยงานอื่น ๆ')], default='SCIENCE', max_length=200),
        ),
    ]
