# Generated by Django 4.2.16 on 2026-05-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อปัญหา')),
                ('category', models.CharField(choices=[('ROADS', 'ถนนและทางเท้า'), ('LIGHTS', 'ไฟฟ้าสาธารณะ'), ('WASTE', 'ขยะและสิ่งแวดล้อม'), ('SAFETY', 'ความปลอดภัย'), ('OTHERS', 'อื่นๆ')], default='ROADS', max_length=20, verbose_name='หมวดหมู่')),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROGRESS', 'กำลังดำเนินการแก้ไข'), ('COMPLETED', 'แก้ไขเสร็จสิ้นแล้ว')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้งเรื่อง')),
            ],
            options={
                'verbose_name': 'ปัญหาที่ร้องเรียน',
                'verbose_name_plural': 'ปัญหาที่ร้องเรียนทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField(verbose_name='ข้อเสนอแนะแนวทางแก้ไข')),
                ('votes', models.IntegerField(default=0, verbose_name='คะแนนโหวตสนับสนุน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เสนอแนะ')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='viable_graph_app.problem', verbose_name='ปัญหาที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ข้อเสนอแนะจากประชาชน',
                'verbose_name_plural': 'ข้อเสนอแนะทั้งหมด',
            },
        ),
    ]
